### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by rolandh** [DevExpress-Examples/how-to-implement-the-context-menu-for-gridcontrol-rows-and-cells#3]
@AndreyMarten is there any way I can contact you outside of github? Skype/gitter etc?

**Comment by AndreyMarten** [comment]
Sure, Roland. We are happy to answer any questions related to our controls in our [Support Center](https://www.devexpress.com/Support/Center/). Please note that you need to have a DX account to ask questions there. If you do not have a DX account yet, you can create one using this link: [Create a New DevExpress Account](https://www.devexpress.com/MyAccount/Register/).
Andrey

**Comment by rolandh** [comment]
It was regarding something other than devexpress
